### ISSUE TITLE
Tests ran in parallel clash with each other

### ISSUE THREAD

**Issue by oryz** [solidtoken/SpecFlow.DependencyInjection#77]
Hi there,

We've been playing around with this SpecFlow plugin, and got it to work for us except for one issue: we don't seem to be able to run tests in parallel. 

For example, the ScenarioContext gets shared between different scenarios that execute at the same time. Another example is that we'd get a clash in the  [ScenarioDependencies] method if we don't put a lock in it.

Is the reason for this related to the limitations described in PR https://github.com/solidtoken/SpecFlow.DependencyInjection/pull/74?

**Comment by mbhoek** [comment]
Hello @oryz, thanks for your question. Before I dive into this, can you please confirm that this is an issue with the plugin and not one of the restrictions of SpecFlow itself? This document describes how SpecFlow handles parallel execution: https://github.com/SpecFlowOSS/SpecFlow/blob/master/docs/Execution/Parallel-Execution.md

Also I know of this SpecFlow issue: https://github.com/SpecFlowOSS/SpecFlow/issues/2225

Again, I'm most happy to dive into your issue but I am aware of SpecFlow itself having problems with parallel execution so that's why I'd like to confirm it. Hope you understand!

**Comment by oryz** [comment]
Hi Mark and thanks for the response.

I understand the concern you raise, to be completely clear we have a mature solution in which we could run tests in parallel successfully before adding this plug in (due to a refactor we needed a better dependency injection framework than the SpecFlow built in one).

So the issue is definitely not with SpecFlow itself.

Could you first confirm that we _should_ be able to run tests in parallel?

**Comment by mbhoek** [comment]
Ok understood. Marked this as a bug and will investigate.

@oryx Sorry for bothering you, but would it be possible to provide an example of what type of parallel tests fail?
The very limited set in this project won't fail, so that makes it hard to look at the problem. Any help would be appreciated!

**Comment by oryz** [comment]
Not sure what we've done or changed but it's all working good now so closing this issue.
